type User {
  email: String! @unique
}

type Item {
  name: String!
  prices: [Price] @relation
}

type Store {
  name: String!
  location: String!
}

type Brand {
  name: String!
}

type Price {
  amount: String!
  bio: Boolean!
  brand: String
  item: Item!
  price: String!
  store: String!
  unit: String!
}

type Unit {
  name: String!
}

type Query {
  all_items: [Item!]
  all_prices: [Price!]
  all_stores: [Store!]
  all_units: [Unit!]
  all_brands: [Brand!]
}
